### ISSUE TITLE
关于 emacs-29 版本中 modeline 字体的设置

### ISSUE THREAD

**Issue by ymfsing** [DogLooksGood/dogEmacs#3]
在 [modeline font setting](https://github.com/DogLooksGood/dogEmacs/blob/master/elisp/init-font.el#L46) 中，是不是需要加入`(set-face-attribute 'mode-line-active frame :font font-spec)`？

**Comment by DogLooksGood** [comment]
我这里看起来工作是正常的。官方后来给出的方法好像是让 mode-line-active 和 mode-line-inactive 使用 :inherit mode-line.
